packages:
    asm89/stack-cors: v2.1.1
    caxy/php-htmldiff: v0.1.14
    chi-teck/drupal-code-generator: 2.6.1
    clue/stream-filter: v1.6.0
    composer/installers: v1.12.0
    composer/semver: 3.3.2
    consolidation/annotated-command: 4.7.1
    consolidation/config: 2.1.2
    consolidation/filter-via-dot-access-data: 2.0.2
    consolidation/log: 3.0.0
    consolidation/output-formatters: 4.2.3
    consolidation/robo: 4.0.3
    consolidation/self-update: 2.0.5
    consolidation/site-alias: 4.0.0
    consolidation/site-process: 5.2.0
    cweagans/composer-patches: 1.7.2
    davedevelopment/stiphle: 0.9.4
    dflydev/dot-access-data: v3.0.2
    doctrine/annotations: 1.13.3
    doctrine/lexer: 1.2.3
    drupal-ckeditor-libraries-group/codesnippet: 4.20.1
    drupal/admin_toolbar: 3.3.0
    drupal/admin_toolbar_content: 1.3.10
    drupal/admin_toolbar_tools: 3.3.0
    drupal/autosave_form: 1.4.0
    drupal/ckeditor: 1.0.1
    drupal/codesnippet: 1.8.0
    drupal/colorbox: 2.0.0
    drupal/core: 10.0.0-rc2
    drupal/core-composer-scaffold: 10.0.0-rc2
    drupal/crop: 2.3.0
    drupal/ctools: 4.0.3
    drupal/diff: 1.1.0
    drupal/environment_indicator: 4.0.11
    drupal/externalauth: 2.0.3
    drupal/geocoder: 4.4.0
    drupal/geofield: 1.47.0
    drupal/geofield_map: 3.0.4
    drupal/gin: 3.0.0-rc1
    drupal/gin_toolbar: 1.0.0-rc1
    drupal/honeypot: 2.1.2
    drupal/image_widget_crop: 2.4.0
    drupal/leaflet: 10.0.1
    drupal/media_entity_twitter: 2.9.0
    drupal/metatag: 1.22.0
    drupal/noreqnewpass: 1.3.0
    drupal/openid_connect: 3.0.0-alpha2
    drupal/pathauto: 1.11.0
    drupal/rdf: 2.1.1
    drupal/redirect: 1.8.0
    drupal/redis: 1.6.0
    drupal/schema_metatag: 2.4.0
    drupal/seven: 1.0.0-alpha1
    drupal/token: 1.11.0
    drupal/xmlsitemap: 1.4.0
    drush/drush: 11.3.2
    easyrdf/easyrdf: 1.1.1
    egulias/email-validator: 3.2.1
    enlightn/security-checker: v1.10.0
    ezyang/htmlpurifier: v4.16.0
    grasmash/expander: 3.0.0
    guzzlehttp/guzzle: 7.5.0
    guzzlehttp/promises: 1.5.2
    guzzlehttp/psr7: 2.4.3
    itamair/geophp: '1.3'
    j7mbo/twitter-api-php: 1.0.6
    joachim-n/composer-manifest: 1.1.5
    league/container: 4.2.0
    masterminds/html5: 2.7.6
    mkalkbrenner/php-htmldiff-advanced: 0.0.8
    nikic/php-parser: v4.15.2
    pear/archive_tar: 1.4.14
    pear/console_getopt: v1.4.3
    pear/pear-core-minimal: v1.10.11
    pear/pear_exception: v1.0.2
    phootwork/collection: v3.2.1
    phootwork/lang: v3.2.1
    php-http/guzzle7-adapter: 1.0.0
    php-http/httplug: 2.3.0
    php-http/message: 1.13.0
    php-http/message-factory: v1.0.2
    php-http/promise: 1.1.0
    phpowermove/docblock: v4.0
    platformsh/config-reader: 2.4.0
    psr/cache: 3.0.0
    psr/container: 2.0.2
    psr/event-dispatcher: 1.0.0
    psr/http-client: 1.0.1
    psr/http-factory: 1.0.1
    psr/http-message: 1.0.1
    psr/log: 3.0.0
    psy/psysh: v0.11.9
    ralouphie/getallheaders: 3.0.3
    symfony/console: v6.2.1
    symfony/dependency-injection: v6.2.1
    symfony/deprecation-contracts: v3.2.0
    symfony/error-handler: v6.2.1
    symfony/event-dispatcher: v6.2.0
    symfony/event-dispatcher-contracts: v3.2.0
    symfony/filesystem: v6.2.0
    symfony/finder: v6.2.0
    symfony/http-foundation: v6.2.1
    symfony/http-kernel: v6.2.1
    symfony/mime: v6.2.0
    symfony/polyfill-ctype: v1.27.0
    symfony/polyfill-iconv: v1.27.0
    symfony/polyfill-intl-grapheme: v1.27.0
    symfony/polyfill-intl-idn: v1.27.0
    symfony/polyfill-intl-normalizer: v1.27.0
    symfony/polyfill-mbstring: v1.27.0
    symfony/polyfill-php72: v1.27.0
    symfony/polyfill-php80: v1.27.0
    symfony/polyfill-php81: v1.27.0
    symfony/process: v6.2.0
    symfony/psr-http-message-bridge: v2.1.4
    symfony/routing: v6.2.0
    symfony/serializer: v6.2.1
    symfony/service-contracts: v3.1.1
    symfony/string: v6.2.0
    symfony/translation-contracts: v3.2.0
    symfony/validator: v6.2.0
    symfony/var-dumper: v6.2.1
    symfony/var-exporter: v6.2.1
    symfony/yaml: v6.2.0
    twig/twig: v3.4.3
    webflo/drupal-finder: 1.2.2
    willdurand/geocoder: 4.6.0
