packages:
    asm89/stack-cors: 1.3.0
    caxy/php-htmldiff: v0.1.12
    chi-teck/drupal-code-generator: 1.33.1
    clue/stream-filter: v1.5.0
    composer/installers: v1.11.0
    composer/semver: 3.2.2
    consolidation/annotated-command: 4.2.4
    consolidation/config: 1.2.1
    consolidation/filter-via-dot-access-data: 1.0.0
    consolidation/log: 2.0.2
    consolidation/output-formatters: 4.1.2
    consolidation/robo: 2.2.2
    consolidation/self-update: 1.2.0
    consolidation/site-alias: 3.1.0
    consolidation/site-process: 4.1.0
    container-interop/container-interop: 1.2.0
    cweagans/composer-patches: 1.7.0
    davedevelopment/stiphle: 0.9.2
    dflydev/dot-access-data: v1.1.0
    doctrine/annotations: 1.11.1
    doctrine/lexer: 1.2.1
    doctrine/reflection: 1.2.2
    drupal-ckeditor-libraries-group/codesnippet: 4.16.0
    drupal/admin_toolbar: 3.0.0
    drupal/auto_anchors: 1.0.0-alpha1
    drupal/autosave_form: 1.2.0
    drupal/blazy: 2.2.0
    drupal/ckeditor_oembed: 1.3.0
    drupal/codesnippet: 1.7.0
    drupal/colorbox: 1.7.0
    drupal/comment_notify: 1.2.0
    drupal/config_filter: 2.2.0
    drupal/config_ignore: 2.3.0
    drupal/core: 9.1.8
    drupal/core-composer-scaffold: 9.1.8
    drupal/core-recommended: 9.1.8
    drupal/crop: 2.1.0
    drupal/ctools: 3.6.0
    drupal/diff: 1.0.0
    drupal/environment_indicator: 4.0.3
    drupal/externalauth: 1.3.0
    drupal/file_mdm: 2.1.0
    drupal/flocblock: 1.0.0
    drupal/geocoder: 3.20.0
    drupal/geofield: 1.22.0
    drupal/geofield_map: 2.67.0
    drupal/gin: 3.0.0-alpha34
    drupal/gin_toolbar: 1.0.0-beta15
    drupal/image_widget_crop: 2.3.0
    drupal/imagemagick: 3.1.0
    drupal/leaflet: 2.1.13
    drupal/matomo: 1.11.0
    drupal/matomo_reports: 1.0.0
    drupal/media_entity_twitter: 2.7.0
    drupal/metatag: 1.16.0
    drupal/noreqnewpass: 1.2.0
    drupal/openid_connect: 2.0.0-alpha5
    drupal/pathauto: 1.8.0
    drupal/redirect: 1.6.0
    drupal/redis: 1.5.0
    drupal/slick: 2.3.0
    drupal/slick_extras: 1.0.0-rc4
    drupal/sophron: 1.1.0
    drupal/token: 1.9.0
    drupal/xmlsitemap: 1.0.0
    drush/drush: 10.5.0
    egulias/email-validator: 2.1.22
    enlightn/security-checker: v1.9.0
    ezyang/htmlpurifier: v4.13.0
    fileeye/mimemap: 1.1.5
    grasmash/expander: 1.0.0
    grasmash/yaml-expander: 1.4.0
    guzzlehttp/guzzle: 6.5.5
    guzzlehttp/promises: 1.4.0
    guzzlehttp/psr7: 1.7.0
    j7mbo/twitter-api-php: 1.0.6
    joachim-n/composer-manifest: 1.1.3
    laminas/laminas-diactoros: 2.5.0
    laminas/laminas-escaper: 2.7.0
    laminas/laminas-feed: 2.13.0
    laminas/laminas-stdlib: 3.3.0
    laminas/laminas-zendframework-bridge: 1.1.1
    league/container: 2.5.0
    lsolesen/pel: 0.9.10
    masterminds/html5: 2.7.4
    mkalkbrenner/php-htmldiff-advanced: 0.0.8
    nikic/php-parser: v4.10.5
    pear/archive_tar: 1.4.13
    pear/console_getopt: v1.4.3
    pear/pear-core-minimal: v1.10.10
    pear/pear_exception: v1.0.1
    phayes/geophp: '1.2'
    phenx/php-font-lib: 0.5.2
    php-http/guzzle6-adapter: v2.0.2
    php-http/httplug: 2.2.0
    php-http/message: 1.11.0
    php-http/message-factory: v1.0.2
    php-http/promise: 1.1.0
    platformsh/config-reader: 2.4.0
    psr/container: 1.0.0
    psr/http-client: 1.0.1
    psr/http-factory: 1.0.1
    psr/http-message: 1.0.1
    psr/log: 1.1.3
    psy/psysh: v0.10.8
    ralouphie/getallheaders: 3.0.3
    stack/builder: v1.0.6
    symfony-cmf/routing: 2.3.3
    symfony/console: v4.4.19
    symfony/debug: v4.4.19
    symfony/dependency-injection: v4.4.19
    symfony/error-handler: v4.4.19
    symfony/event-dispatcher: v4.4.19
    symfony/event-dispatcher-contracts: v1.1.9
    symfony/filesystem: v4.4.22
    symfony/finder: v5.2.8
    symfony/http-client-contracts: v2.3.1
    symfony/http-foundation: v4.4.19
    symfony/http-kernel: v4.4.19
    symfony/mime: v5.1.11
    symfony/polyfill-ctype: v1.20.0
    symfony/polyfill-iconv: v1.20.0
    symfony/polyfill-intl-idn: v1.20.0
    symfony/polyfill-intl-normalizer: v1.20.0
    symfony/polyfill-mbstring: v1.20.0
    symfony/polyfill-php72: v1.22.1
    symfony/polyfill-php73: v1.22.1
    symfony/polyfill-php80: v1.20.0
    symfony/process: v4.4.19
    symfony/psr-http-message-bridge: v2.0.2
    symfony/routing: v4.4.19
    symfony/serializer: v4.4.19
    symfony/service-contracts: v2.2.0
    symfony/translation: v4.4.19
    symfony/translation-contracts: v2.3.0
    symfony/validator: v4.4.19
    symfony/var-dumper: v5.1.11
    symfony/yaml: v4.4.19
    twig/twig: v2.14.1
    typo3/phar-stream-wrapper: v3.1.6
    webflo/drupal-finder: 1.2.2
    webmozart/assert: 1.10.0
    webmozart/path-util: 2.3.0
    willdurand/geocoder: 4.4.0
