<?php

declare(strict_types=1);

/**
 * @file
 * Provides entity templates for the Orienteer module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function orienteer_theme(): array {
  return [
    'orienteer_event' => ['render element' => 'elements'],
    'orienteer_location' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for event templates.
 *
 * Default template: orienteer-event.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the event information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_orienteer_event(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function orienteer_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish events.
      $storage = \Drupal::entityTypeManager()->getStorage('orienteer_event');
      $orienteer_event_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($orienteer_event_ids) as $orienteer_event) {
        $orienteer_event->set('status', FALSE)->save();
      }

      // Unpublish locations.
      $storage = \Drupal::entityTypeManager()->getStorage('orienteer_location');
      $orienteer_location_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($orienteer_location_ids) as $orienteer_location) {
        $orienteer_location->set('status', FALSE)->save();
      }

      break;

    case 'user_cancel_reassign':
      // Anonymize events.
      $storage = \Drupal::entityTypeManager()->getStorage('orienteer_event');
      $orienteer_event_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($orienteer_event_ids) as $orienteer_event) {
        $orienteer_event->setOwnerId(0)->save();
      }

      // Anonymize locations.
      $storage = \Drupal::entityTypeManager()->getStorage('orienteer_location');
      $orienteer_location_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($orienteer_location_ids) as $orienteer_location) {
        $orienteer_location->setOwnerId(0)->save();
      }

      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function orienteer_user_predelete(UserInterface $account): void {
  // Delete events that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('orienteer_event');
  $orienteer_event_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($orienteer_event_ids)
  );
  // Delete old revisions.
  $orienteer_event_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($orienteer_event_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }

  // Delete locations that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('orienteer_location');
  $orienteer_location_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($orienteer_location_ids)
  );
  // Delete old revisions.
  $orienteer_location_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($orienteer_location_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}

/**
 * Prepares variables for location templates.
 *
 * Default template: orienteer-location.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the location information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_orienteer_location(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
