name: Behaviour Tests
on: [push]

env:
  PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1

      # example: composer install
      - run: ddev composer install

      # Install Psh CLI.
      - name: Install Psh CLI
        run: curl -sS https://platform.sh/cli/installer | php

      # If you need to connect to database.
      - name: Load certificate
        run: ~/.platformsh/bin/platform ssh-cert:load -y -vvv

      - name: Add Psh to trusted keys
        run: |
          ssh-keyscan ssh.uk-1.platform.sh >> ~/.ssh/known_hosts
          ssh-keyscan git.uk-1.platform.sh >> ~/.ssh/known_hosts

      # Get the database to reflect main and run update.
      - name: Fill database and bring Drupal up to date
        run: |
          ~/.platformsh/bin/platform db:dump --environment=main --project=nlw7xhb3fyt7y --stdout | ddev mysql
          ddev exec drush -y cache-rebuild
          ddev exec drush -y updatedb
          ddev exec drush -y config-import

      # Finally, run the tests.
      - name: Run Behat tests
        run: |
          ddev exec behat --colors
