name: Behaviour Tests
on: [pull_request]

env:
  PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:

      # Actions from outside the project must be allowed in the project settings.
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1

      # Composer install
      - run: ddev composer install

      # Get ready to test with an empty-ish site.
      - name: Prime a new empty site to test
        run: |
          ddev exec drush -y site:install
          ddev exec drush -y entity:delete shortcut
          ddev exec drush -y config:set system.site uuid "457a53ee-ba47-433e-9fc2-314fff8a5c99"
          ddev exec drush -y config:import
          ddev exec drush -y cache:rebuild

      # Finally, run the tests.
      - name: Run Behat tests
        run: |
          ddev exec behat --colors
