name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: php-actions/composer@v6

    - name: PHPUnit Tests
      uses: php-actions/phpunit@master
      env:
        TEST_NAME: Custom Module Tests
      with:
        version: 9.6
        configuration: phpunit.xml
