name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          php_version: 8.2
          php_extensions: date dom filter gd hash json pcre PDO session SimpleXML SPL tokenizer xml

    - uses: php-actions/composer@v6

    - name: PHPUnit Tests
      uses: php-actions/phpunit@master
      env:
        TEST_NAME: Custom Module Tests
      with:
        configuration: phpunit.xml
