name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: php-actions/composer@v6
      with:
        php_version: "8.2"
        php_extensions: date dom filter gd hash json pcre PDO session SimpleXML SPL tokenizer xml

    - name: PHPUnit Tests
      uses: php-actions/phpunit@master
      env:
        TEST_NAME: Custom Module Tests
      with:
        version: 9.6
        configuration: phpunit.xml

