name: RachelNorfolk Custom Modules

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: gdate, dom, filter, gd, hash, json, pcre, PDO, session, SimpleXML, SPL, tokenizer, xml

    - name: Composer Install
      run: |
        composer --no-interaction --no-progress --optimize-autoloader install

    - name: Webserver
      run: |
        nohup php -S 0.0.0.0:8000 -t web > phpd.log 2>&1 &
        sed -i "s/\/localhost/\/localhost:8000/g" phpunit.xml

    - name: PHPUnit Tests
      run: |
        ./vendor/bin/phpunit web/modules/custom

    - name: Check Drupal Coding Standards
      run: |
        ./vendor/bin/phpcs --config-set installed_paths ./vendor/drupal/coder/coder_sniffer
        ./vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,install,js web/modules/custom
